/* Cassandra Chavez-Suarez
COMP 333
4/26/18
Project #4*/
female(fabiana).
female(teresa).
female(irma).
female(noemi).
female(miroslava).
female(rosario).
female(garmy).
female(cassandra).
female(jessica).
female(brittany).
male(donaciano).
male(arturo).
male(alex).
male(hector).
male(juan).
male(oscar).
male(erik).
parent(fabiana,teresa).
parent(donaciano,teresa).
parent(teresa,irma).
parent(teresa,noemi).
parent(teresa,miroslava).
parent(teresa,rosario).
parent(teresa,garmy).
parent(teresa,hector).
parent(teresa,juan).
parent(arturo,irma).
parent(arturo,noemi).
parent(arturo,miroslava).
parent(arturo,rosario).
parent(arturo,garmy).
parent(arturo,hector).
parent(arturo,juan).
parent(irma,cassandra).
parent(irma,oscar).
parent(irma,jessica).
parent(irma,erik).
parent(irma,brittany).
parent(alex,cassandra).
parent(alex,oscar).
parent(alex,jessica).
parent(alex,erik).
parent(alex,brittany).
mother(X,Y):-female(X),parent(X,Y).
father(X,Y):-male(X),parent(X,Y).
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
grandmother(X,Y):-female(X),grandparent(X,Y).
grandfather(X,Y):-male(X),grandparent(X,Y).
ancestor(X,Y):-parent(X,Y).
ancestor(X,Y):-parent(X,Z),ancestor(Z,Y).
sibling(X,Y):-parent(Z,X),parent(Z,Y),not(X=Y).
aunt(X,Y):-sister(X,Z),parent(Z,Y).
uncle(X,Y):-brother(X,Z),parent(Z,Y).
sister(X,Y):-female(X),sibling(X,Y).
brother(X,Y):-male(X),sibling(X,Y).
descendant(X,Y):-parent(Y,X).
descendant(X,Y):-grandparent(Y,X).
descendant(X,Y):-parent(Y,Z),descendant(X,Z).
findParents(X,L):-setof(Z,parent(Z,X),L).
findGrandparents(X,L):-setof(Z,grandparent(Z,X),L).
findChildren(X,L):-setof(Z,parent(X,Z),L).
findSiblings(X,L):-setof(Z,sibling(Z,X),L).
findAncestors(X,L):-setof(Z,ancestor(Z,X),L).
findDescendants(X,L):-setof(Z,descendant(Z,X),L).
ancestorPath(X,X,[X]).
ancestorPath(X,Y,[X|T]):-parent(X,Z),ancestorPath(Z,Y,T).
